spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/innsight_new}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
